stages:
  - build
  - publish

variables:
  NPM_TOKEN: $NPM_TOKEN
  NODE_ENV: production

build:
  stage: build
  image: node:$NODE_VERSION
  services:
    - docker:dind
  script:
    - npm install  # Installe les dépendances avant de construire
    - npm run build
    - npm test
  only:
    - main
  parallel:
    matrix:
      - NODE_VERSION: ["14", "16", "18", "20", "22"]

publish:
  stage: publish
  image: node:22
  needs:
    - build
  script:
    - npm install  # Installe les dépendances avant de construire
    - npm run build
    - npm test
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    - npm publish
  only:
    - main
  dependencies:
    - build
