stages:
  - build
  - test

variables:
  NPM_TOKEN: $NPM_TOKEN

build:
  stage: build
  image: node:$NODE_VERSION
  script:
    - npm install -g typescript  # Installe TypeScript globalement
    - npm install  # Installe toutes les dépendances (y compris devDependencies)
    - npm run build  # Compile le projet
  only:
    - main
  parallel:
    matrix:
      - NODE_VERSION: ["14", "16", "18", "20", "22"]

test:
  stage: test
  image: node:$NODE_VERSION
  script:
    - npm install  # Installe toutes les dépendances (y compris devDependencies)
    - npm test  # Exécute les tests
  only:
    - main
  parallel:
    matrix:
      - NODE_VERSION: ["14", "16", "18", "20", "22"]
